# On écoute sur le port standard sécurisé
listener 8883

# Chemins vers tes certificats (adapte si besoin)
cafile certs/ca.crt
certfile certs/server.crt
keyfile certs/server.key

# Sécurité supplémentaire
tls_version tlsv1.2
allow_anonymous true